<?php

declare(strict_types=1);

namespace App\Http\Controllers\Portal;

use App\Enums\OrderStatus;
use App\Models\Order\Order;
use App\Models\Order\OrderItem;
use App\Models\Order\OrderPayment;
use App\Models\Order\ReturnOrder;
use App\Models\Scopes\OrganizationScope;
use App\Services\Documents\DocumentPdfService;
use App\Services\ReturnOrderService;
use App\Support\Money;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;
use Symfony\Component\HttpFoundation\Response as HttpResponse;

/**
 * A customer's orders: list, detail and invoice PDF.
 *
 * Only customer-facing fields are sent to the page. Staff notes, metadata,
 * the creator and approval notes stay internal.
 */
class PortalOrderController extends PortalController
{
    public function index(Request $request): Response
    {
        $contact = $this->contact($request);

        $orders = $this->orders($contact)
            ->withCount('items')
            ->latest('order_date')
            ->latest('id')
            ->paginate(15)
            ->withQueryString()
            ->through(fn (Order $order) => $this->orderSummary($order) + ['items_count' => $order->items_count]);

        return Inertia::render('Portal/Orders/Index', [
            'orders' => $orders,
        ]);
    }

    public function show(Request $request, string $order, ReturnOrderService $returnsService): Response
    {
        $contact = $this->contact($request);
        $order = $this->findOrder($contact, $order);
        $order->load('items');

        $returned = $returnsService->returnedQuantities($order);
        $items = $order->items->map(fn (OrderItem $item) => $this->lineSummary($item, (int) $returned->get($item->id, 0)))->values();

        $returns = $this->returns($contact)
            ->where('order_id', $order->id)
            ->latest('id')
            ->get()
            ->map(fn (ReturnOrder $r) => $this->returnSummary($r))
            ->values();

        // Payments the customer made (and refunds they received). Voided rows
        // were mistakes; references and notes are internal bookkeeping.
        $payments = $order->payments()
            ->withoutGlobalScope(OrganizationScope::class)
            ->where('organization_id', $order->organization_id)
            ->whereNull('voided_at')
            ->orderBy('paid_at')
            ->get()
            ->map(fn (OrderPayment $payment) => [
                'id' => $payment->id,
                'type' => $payment->type?->value,
                'amount' => $payment->amount,
                'method' => $payment->method?->value,
                'method_label' => $payment->method?->label(),
                'paid_at' => $payment->paid_at?->toIso8601String(),
            ])
            ->values();

        return Inertia::render('Portal/Orders/Show', [
            'order' => $this->orderSummary($order) + [
                'discount_type' => $order->discount_type?->value,
                'discount_value' => $order->discount_value,
                'discount_amount' => $order->discount_amount,
                'amount_paid' => $order->amount_paid,
                'balance_due' => Money::max('0', Money::subtract($order->total, $order->amount_paid ?? '0')),
                'payment_status' => $order->payment_status?->value,
                'payments' => $payments,
                'subtotal' => $order->subtotal,
                'tax' => $order->tax,
                'shipping' => $order->shipping,
                'customer_address' => $order->customer_address,
                'items' => $items,
                'invoice_available' => $this->invoiceAvailable($order),
                'can_request_return' => $order->status === OrderStatus::DELIVERED
                    && $items->contains(fn (array $line) => $line['returnable_quantity'] > 0),
            ],
            'returns' => $returns,
        ]);
    }

    /**
     * Download the order's invoice PDF, generated by the same service the
     * staff download and the invoice email use.
     */
    public function invoice(Request $request, string $order, DocumentPdfService $pdfs): HttpResponse
    {
        $contact = $this->contact($request);
        $order = $this->findOrder($contact, $order);

        abort_unless($this->invoiceAvailable($order), 404);

        $pdf = $pdfs->orderInvoice($order);

        return $pdf->download($pdfs->orderInvoiceFilename($order));
    }
}
